services:
  combat-service:
    build: ./combat
    container_name: combat-api
    depends_on:
      - rabbitmq
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    networks:
      - erjulrian-network
    restart: always

  log-service:
    build: ./log
    container_name: log-api
    depends_on:
      - rabbitmq
      - elasticsearch
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - erjulrian-network
    restart: always

  hero-service:
    build: ./hero
    container_name: hero-api
    depends_on:
      - db
      - rabbitmq
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=hero_user
      - DB_PASSWORD=hero_password
      - DB_NAME=erjulrian_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - erjulrian-network
    restart: always

  inventory-service:
    build: ./inventory
    container_name: inventory-api
    depends_on:
      - db
      - rabbitmq
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=inventory_user
      - DB_PASSWORD=inventory_password
      - DB_NAME=erjulrian_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - erjulrian-network
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erjulrian-network

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: log-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - erjulrian-network
    restart: always
  
  db:
    image: postgres:16-alpine
    container_name: erjulrian-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=toto123
      - POSTGRES_DB=erjulrian_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - erjulrian-network


volumes:
  db-data:

networks:
  erjulrian-network:
    driver: bridge

